
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - my_network

  frontend:
    build:
      context: ./frontVue
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - my_network

  backend:
    build:
      context: ./express_back
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/express_app_charvela
    networks:
      - my_network

networks:
  my_network:
