
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  frontend:
    build:
      context: ./frontVue
    ports:
      - "8080:8080"
    depends_on:
      - backend

  backend:
    build:
      context: ./express_back
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment: 
      - MONGO_URI=mongodb://mongodb:27017/tu_db_nombre
